CREATE TABLE `germes_multibasket` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `BASKET_ID` INT(11) NOT NULL,
    `ORDER_ID` INT(11) NULL,
    `PRODUCT_ID` INT(11) NOT NULL,
    `BASKET_ITEM_ROW` VARCHAR (65536) NOT NULL,
    `SORT` INT(11) DEFAULT 500,
    `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `DATE_INSERT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    INDEX (`BASKET_ID`)
);
CREATE TABLE `germes_multibasket_history` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `BASKET_ID` INT(11) NOT NULL,
    `ORDER_ID` INT(11) NULL,
    `PRODUCT_ID` INT(11) NOT NULL,
    `TYPE` VARCHAR (256) NOT NULL DEFAULT 'INFO',
    `BASKET_ITEM_ROW` VARCHAR (65536) NOT NULL,
    `DESCRIPTION` VARCHAR (65536) NOT NULL,
    `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    INDEX (`BASKET_ID`)
);
CREATE TABLE `germes_multibasket_contragents` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR (65536) NOT NULL,
    `DESCRIPTION` VARCHAR (65536) NOT NULL,
    `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `DATE_INSERT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    INDEX (`BASKET_ID`)
);
